services:
  # MongoDB service
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - mern-network

  # Server service (Express app)
  server:
    build: ./server
    container_name: server
    ports:
      - "9000:9000"
    networks:
      - mern-network
    depends_on:
      - mongodb


  # Client service (React app)
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - mern-network
    depends_on:
      - server

networks:
  mern-network:
    driver: bridge
